language: java
jdk: oraclejdk8
install: true
script:
  - npm install -g serverless
  - npm install -g yarn
  - mvn clean install
  - sls deploy
  - cd frontend && npm install
  - cd frontend && yarn deploy
