language: java
jdk: oraclejdk8
install: true
script:
  - npm install -g serverless
  - npm install -g yarn
  - cd frontend/movie-rating && npm install && yarn deploy
  - mvn clean install
  - sls deploy
