language: java
jdk: oraclejdk8
install: true
script:
  - npm install -g serverless
  - npm install -g yarn
  - ls movie-rating/
  - ls frontend
  - cd frontend && npm install && yarn deploy
  - ls -la
  - mvn clean install
  - sls deploy
