language: java
jdk: oraclejdk8
install: true
script:
  - npm install -g serverless
  - npm install -g yarn
  - ls -la
  - cd movie-rating/frontend && npm install && yarn deploy
  - ls -la
  - mvn clean install
  - sls deploy
