version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g yarn
      - npm install -g serverless
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - yarn deploy
      - serverless deploy --stage prod
